Make it optional to offer npm publish rights
cordova/new_committer_and_pmc pull request #21
Opened 2019-10-15 19:23 UTC by brodybits

Followup to PR #20:

Unfortunately I did not see <https://github.com/apache/cordova-new-committer-and-pmc/pull/20#issuecomment-542362229> by @purplecabbage before merging #20.

While I would agree with <https://github.com/apache/cordova-new-committer-and-pmc/pull/20#issuecomment-542362229>, I do think this is a step that should not be forgotten when onboarding new committers.

I think it would be ideal to have a more gradual onboarding process for new members. This may involve a change in our process. Any ideas or suggestions?

/cc @purplecabbage @timbru31

2019-10-15 21:45 UTC, jcesarmobile commented
I agree with purplecabbage, the npm permission should be granted by request to avoid some new committer to publish a package without following the apache process because of not knowing about it. If somebody want to do a release, they will ask about the permissions, then can be told about the process.

2019-10-15 21:54 UTC, brodybits commented
Thanks @jcesarmobile. Does that mean we should merge this proposal, or maybe do something else?

If we should do something else, would you mind showing a suggested change?

I am finishing up now, can take another look tomorrow. I wouldn't mind if others decide to fix it a different way.

2019-12-13 09:04 UTC, timbru31 requested changes

2019-12-13 09:04 UTC, timbru31 commented on .github/ISSUE_TEMPLATE/NEW_COMMITTER_AND_PMC.md
> +- [ ] 11. Optional: offer npm publish rights to the new PMC member
```suggestion
- [ ] 11. Optional: offer npm publish rights to the new PMC member, if requested and required
```

Just a suggestion though

2019-12-16 13:16 UTC, timbru31 approved these changes

2019-12-16 14:25 UTC, merged